BaseURL = "https://mcho.dev/"
LanguageCode = "ja-JP"
HasCJKLanguage = true
title = "Mcho"
theme = "primer"
summaryLength = 100
# Code pen
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = "UA-133713641-1"
publishDir = "docs"
enableGitInfo = true
copyright = "&copy; mcho 2019"
rssLimit = 15
disqusShortname = "mity"

[Author]
  Name = "mcho"

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[params]
  Subtitle = ""
  Twitter = "mcho71"
  GitHub = "mcho71"
  DateFormat = "2006-01-02"
  MonthFormat = "2006-01"
  shareTo = ["Twitter", "Hatena"]
  creditHugoPrimer = true
  useIcon = true
  UseTwitterCard = true
  mainSections = ["notes", "memos"]

[related]
  threthold = 80
  includeNewer = true
  toLower = false
[[related.indices]]
  name = "tags"
  weight = 80
[[related.indices]]
  name = "categories"
  weight = 80
